volumes:
  postgres_data:
  elasticsearch_data:
networks:
  default:

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch_container
    ports:
      - 9200:9200
    env_file:
      - .env
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    healthcheck:
      test: "curl http://localhost:9200/_cluster/health"
      interval: 3s
      timeout: 10s
      retries: 20
    networks:
      - default

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    container_name: postgres_container
    ports:
      - 6666:5432                                    # port exposed for dbeaver
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 5s
      retries: 6
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - default

  python_app:
    build: ./app
    env_file:
      - .env
    container_name: python_app_container
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - default